#!/usr/bin/env bash
#MISE description="Watch mode for development with sourcemaps"

bun build ./src/index.ts \
  --outdir dist \
  --target bun \
  --sourcemap=inline \
  --external '@sentry/bun' \
  --external '@opentelemetry/api' \
  --external '@opencode-ai/plugin' \
  --watch
